### ISSUE TITLE
Add c.suggest

### ISSUE THREAD

**Issue by friedkeenan** [Sun-Research-University/Marina-Bot#1]
![image](https://user-images.githubusercontent.com/20881398/59406819-0240c500-8d75-11e9-9d29-c003ab34fdd4.png)

**Comment by gabehxd** [comment]
no

**Comment by noahc3** [comment]
Disappointing, this is a trivial yet necessary feature and without it I don't think Connor can live up to the holyness that was Sombra Bot 😢😢😢😢😢😢

🔨

**Comment by AnnsAnns** [comment]
Boo Sun, boo

**Comment by friedkeenan** [comment]
Sun bad

**Comment by gabehxd** [comment]
shut

**Comment by noahc3** [comment]
n

**Comment by gabehxd** [comment]
![image](https://user-images.githubusercontent.com/22406854/71776033-1598c500-2f3f-11ea-9488-29f21f2c3df1.png)
